
#include "circ_menu.h"
#include "circ_pause.h"
#include "circ_mute.h"
#include "circ_next.h"
#include "circ_play.h"
#include "circ_prev.h"

#include "circ_audio0.h"
#include "circ_audio100.h"
#include "circ_music.h"
#include "Apps-Calc-icon.h"
#include "Apps-Clock-icon.h"
#include "Apps-Gallery-icon.h"
#include "Apps-Preferences-Desktop-C-icon.h"
#include "Apps-Phone-icon.h"
#include "Apps-Subtitleeditor-icon.h"
#include "Apps-Rubrica-icon.h"
#include "Apps-Player-Audio-C-icon.h"

#include "battery-1-16.h"
#include "battery-2-16.h"
#include "battery-3-16.h"
#include "battery-empty16.h"
#include "battery-full16.h"
#include "battery-half16.h"